version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5464:5432"

  loader:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/app/

  runner:
    image: entsupml/unison-runner:0.4.2
    environment:
      UNISON_API_TOKEN: ${UNISON_API_TOKEN}
      UNISON_DSN: "postgresql+psycopg2://postgres:postgres@db/postgres"
