version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5464:5432"

  runner_and_loader:
    build: .
    depends_on:
      - db
    environment:
      UNISON_API_TOKEN: ${UNISON_API_TOKEN}
      UNISON_DSN: "postgresql+psycopg2://postgres:postgres@db/postgres"
    volumes:
      - ./csv:/loader/csv
